-- 为管理员表添加主题偏好字段
ALTER TABLE CJ_ADM_ADMINISTRATOR ADD (
    THEME_PREF VARCHAR2(20) DEFAULT 'theme1',
    THEME_UPDATE_TIME DATE
);

-- 添加注释
COMMENT ON COLUMN CJ_ADM_ADMINISTRATOR.THEME_PREF IS '用户主题偏好：theme1-阿里蓝，theme2-Material 紫，theme3-腾讯深蓝，theme4-清新绿，theme5-经典黑金';
COMMENT ON COLUMN CJ_ADM_ADMINISTRATOR.THEME_UPDATE_TIME IS '主题更新时间';

-- 更新现有用户默认为 theme1
UPDATE CJ_ADM_ADMINISTRATOR SET THEME_PREF = 'theme1' WHERE THEME_PREF IS NULL;

COMMIT;

-- 验证
SELECT USERNAME, REAL_NAME, THEME_PREF FROM CJ_ADM_ADMINISTRATOR;
