-- Test Data for CJCMS (Without N' prefix)
-- Execute in SQL*Plus or PL/SQL Developer

SET DEFINE OFF;

PROMPT Inserting test data...

-- Clear existing data
DELETE FROM CJ_USER_SUBMISSION;
DELETE FROM CJ_USER_USER;
DELETE FROM CJ_USER_GROUP;
DELETE FROM CJ_CMS_CONTENT;
DELETE FROM CJ_CMS_MODEL_FIELD;
DELETE FROM CJ_CMS_MODEL;
DELETE FROM CJ_CMS_CHANNEL;
DELETE FROM CJ_SYS_SITE;
DELETE FROM CJ_ADM_ADMIN_ROLE;
DELETE FROM CJ_ADM_ROLE_MENU;
DELETE FROM CJ_ADM_DATA_PERMISSION;
DELETE FROM CJ_ADM_ROLE;
DELETE FROM CJ_ADM_ADMINISTRATOR;
DELETE FROM CJ_SYS_CONFIG;
COMMIT;

-- Administrator
INSERT INTO CJ_ADM_ADMINISTRATOR (ADMIN_ID, USERNAME, PASSWORD_HASH, REAL_NAME, EMAIL, DEPARTMENT, POSITION, STATUS) 
VALUES ('admin001', 'admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lqkkO9QS3TzCjH3rS', '超级管理员', 'admin@cjcms.com', '技术部', '系统管理员', 1);

-- Roles
INSERT INTO CJ_ADM_ROLE (ROLE_ID, ROLE_NAME, ROLE_CODE, ROLE_TYPE, DESCRIPTION, DATA_SCOPE_TYPE, STATUS) 
VALUES ('role001', '超级管理员', 'super_admin', 1, '系统超级管理员，拥有所有权限', 'ALL', 1);

INSERT INTO CJ_ADM_ROLE (ROLE_ID, ROLE_NAME, ROLE_CODE, ROLE_TYPE, DESCRIPTION, DATA_SCOPE_TYPE, STATUS) 
VALUES ('role002', '站点管理员', 'site_admin', 2, '站点管理员，管理指定站点', 'SITE', 1);

INSERT INTO CJ_ADM_ROLE (ROLE_ID, ROLE_NAME, ROLE_CODE, ROLE_TYPE, DESCRIPTION, DATA_SCOPE_TYPE, STATUS) 
VALUES ('role003', '内容编辑', 'content_editor', 2, '内容编辑，负责内容创建和编辑', 'CHANNEL', 1);

-- Admin-Role Relation
INSERT INTO CJ_ADM_ADMIN_ROLE (ADMIN_ID, ROLE_ID) VALUES ('admin001', 'role001');

-- Site
INSERT INTO CJ_SYS_SITE (SITE_ID, SITE_NAME, SITE_CODE, DOMAIN, STATUS, DESCRIPTION, CREATE_USER_ID) 
VALUES ('site001', '长江 CMS 主站', 'main_site', 'http://www.cjcms.com', 1, '长江 CMS 官方主站', 'admin001');

-- Channels
INSERT INTO CJ_CMS_CHANNEL (CHANNEL_ID, SITE_ID, CHANNEL_NAME, CHANNEL_CODE, CHANNEL_TYPE, ORDER_NUM, CREATE_USER_ID) 
VALUES ('channel001', 'site001', '根栏目', 'root', 1, 0, 'admin001');

INSERT INTO CJ_CMS_CHANNEL (CHANNEL_ID, SITE_ID, PARENT_ID, CHANNEL_NAME, CHANNEL_CODE, CHANNEL_TYPE, ORDER_NUM, CREATE_USER_ID) 
VALUES ('channel002', 'site001', 'channel001', '公司新闻', 'news', 1, 1, 'admin001');

INSERT INTO CJ_CMS_CHANNEL (CHANNEL_ID, SITE_ID, PARENT_ID, CHANNEL_NAME, CHANNEL_CODE, CHANNEL_TYPE, ORDER_NUM, CREATE_USER_ID) 
VALUES ('channel003', 'site001', 'channel001', '产品展示', 'products', 1, 2, 1, 'admin001');

-- Content Model
INSERT INTO CJ_CMS_MODEL (MODEL_ID, SITE_ID, MODEL_NAME, MODEL_CODE, TABLE_NAME, DESCRIPTION, CREATE_USER_ID) 
VALUES ('model001', 'site001', '新闻模型', 'news', 'CJ_CMS_CONTENT_NEWS', '新闻内容模型', 'admin001');

-- Content
INSERT INTO CJ_CMS_CONTENT (CONTENT_ID, SITE_ID, CHANNEL_ID, MODEL_ID, TITLE, AUTHOR, SOURCE, STATUS, VIEW_COUNT, CREATE_USER_ID) 
VALUES ('content001', 'site001', 'channel002', 'model001', '长江 CMS 系统正式发布', '管理员', '原创', 2, 100, 'admin001');

-- Config
INSERT INTO CJ_SYS_CONFIG (CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) 
VALUES ('config001', 'site.title', '长江 CMS', '网站标题');

INSERT INTO CJ_SYS_CONFIG (CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) 
VALUES ('config002', 'site.logo', '/images/logo.png', '网站 Logo');

-- User
INSERT INTO CJ_USER_USER (USER_ID, USERNAME, PASSWORD_HASH, NICKNAME, EMAIL, MOBILE, GENDER, STATUS) 
VALUES ('user001', 'testuser', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lqkkO9QS3TzCjH3rS', '测试用户', 'test@example.com', '13900139000', 1, 1);

-- User Groups
INSERT INTO CJ_USER_GROUP (GROUP_ID, GROUP_NAME, GROUP_CODE, DESCRIPTION, MAX_CONTENT_COUNT, NEED_AUDIT, STATUS) 
VALUES ('group001', '普通会员', 'normal_member', '普通用户组', 10, 1, 1);

INSERT INTO CJ_USER_GROUP (GROUP_ID, GROUP_NAME, GROUP_CODE, DESCRIPTION, MAX_CONTENT_COUNT, NEED_AUDIT, STATUS) 
VALUES ('group002', 'VIP 会员', 'vip_member', 'VIP 用户组', 100, 0, 1);

COMMIT;

PROMPT ========================================
PROMPT Test data inserted successfully!
PROMPT ========================================
PROMPT Default accounts:
PROMPT   Username: admin
PROMPT   Password: admin123
PROMPT ========================================
