-- CJCMS Database Schema - NVARCHAR2 Version (Best for Chinese)
-- All Chinese text fields use NVARCHAR2 for full Unicode support
-- Compatible with ZHS16GBK database

PROMPT Dropping existing tables...
BEGIN
  FOR rec IN (SELECT table_name FROM user_tables WHERE table_name LIKE 'CJ_%') LOOP
    EXECUTE IMMEDIATE 'DROP TABLE "' || rec.table_name || '" CASCADE CONSTRAINTS';
  END LOOP;
END;
/
COMMIT;

PROMPT Creating tables with NVARCHAR2 for Chinese support...

-- 1. Site Table
CREATE TABLE CJ_SYS_SITE (
  SITE_ID          VARCHAR2(40) NOT NULL,
  SITE_NAME        NVARCHAR2(100) NOT NULL,
  SITE_CODE        VARCHAR2(50) NOT NULL,
  PARENT_SITE_ID   VARCHAR2(40),
  DOMAIN           NVARCHAR2(200),
  STATUS           NUMBER(1) DEFAULT 1 NOT NULL,
  DEFAULT_LANGUAGE VARCHAR2(10) DEFAULT 'zh-CN' NOT NULL,
  TIMEZONE         VARCHAR2(50) DEFAULT 'Asia/Shanghai' NOT NULL,
  LOGO_URL         NVARCHAR2(300),
  DESCRIPTION      NVARCHAR2(500),
  CREATE_USER_ID   VARCHAR2(40) NOT NULL,
  CREATE_TIME      DATE DEFAULT SYSDATE NOT NULL,
  UPDATE_USER_ID   VARCHAR2(40),
  UPDATE_TIME      DATE,
  CONSTRAINT PK_CJ_SYS_SITE PRIMARY KEY (SITE_ID),
  CONSTRAINT FK_SITE_PARENT FOREIGN KEY (PARENT_SITE_ID) REFERENCES CJ_SYS_SITE(SITE_ID)
);

COMMENT ON TABLE CJ_SYS_SITE IS '站点表';
COMMENT ON COLUMN CJ_SYS_SITE.SITE_NAME IS '站点名称';
COMMENT ON COLUMN CJ_SYS_SITE.DESCRIPTION IS '站点描述';

CREATE UNIQUE INDEX UK_SITE_CODE ON CJ_SYS_SITE(SITE_CODE);

-- 2. Menu Table
CREATE TABLE CJ_SYS_MENU (
  MENU_ID          VARCHAR2(40) NOT NULL,
  PARENT_ID        VARCHAR2(40),
  MENU_NAME        NVARCHAR2(100) NOT NULL,
  MENU_CODE        VARCHAR2(100) NOT NULL,
  MENU_TYPE        NUMBER(1) DEFAULT 1 NOT NULL,
  ROUTE_PATH       NVARCHAR2(200),
  COMPONENT_PATH   NVARCHAR2(200),
  ICON             NVARCHAR2(100),
  ORDER_NUM        NUMBER(10) DEFAULT 0,
  IS_VISIBLE       NUMBER(1) DEFAULT 1 NOT NULL,
  PERMISSION_CODE  VARCHAR2(100),
  DESCRIPTION      NVARCHAR2(200),
  STATUS           NUMBER(1) DEFAULT 1 NOT NULL,
  CREATE_TIME      DATE DEFAULT SYSDATE NOT NULL,
  UPDATE_TIME      DATE,
  CONSTRAINT PK_CJ_SYS_MENU PRIMARY KEY (MENU_ID),
  CONSTRAINT FK_MENU_PARENT FOREIGN KEY (PARENT_ID) REFERENCES CJ_SYS_MENU(MENU_ID)
);

COMMENT ON TABLE CJ_SYS_MENU IS '菜单表';
COMMENT ON COLUMN CJ_SYS_MENU.MENU_NAME IS '菜单名称';
COMMENT ON COLUMN CJ_SYS_MENU.DESCRIPTION IS '描述';

CREATE UNIQUE INDEX UK_MENU_CODE ON CJ_SYS_MENU(MENU_CODE);

-- 3. Config Table
CREATE TABLE CJ_SYS_CONFIG (
  CONFIG_ID        VARCHAR2(40) NOT NULL,
  CONFIG_KEY       VARCHAR2(100) NOT NULL,
  CONFIG_VALUE     NVARCHAR2(2000),
  CONFIG_TYPE      VARCHAR2(20) DEFAULT 'STRING' NOT NULL,
  DESCRIPTION      NVARCHAR2(200),
  UPDATE_TIME      DATE,
  CONSTRAINT PK_CJ_SYS_CONFIG PRIMARY KEY (CONFIG_ID)
);

COMMENT ON TABLE CJ_SYS_CONFIG IS '系统配置表';
CREATE UNIQUE INDEX UK_CONFIG_KEY ON CJ_SYS_CONFIG(CONFIG_KEY);

-- 4. Operation Log
CREATE TABLE CJ_SYS_OPERATION_LOG (
  LOG_ID           VARCHAR2(40) NOT NULL,
  OPERATOR_ID      VARCHAR2(40) NOT NULL,
  OPERATION_TYPE   VARCHAR2(50) NOT NULL,
  MODULE           VARCHAR2(50) NOT NULL,
  REQUEST_URL      NVARCHAR2(300),
  IP_ADDRESS       VARCHAR2(50),
  CREATE_TIME      DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_CJ_SYS_OPERATION_LOG PRIMARY KEY (LOG_ID)
);

-- 5. Error Log
CREATE TABLE CJ_SYS_ERROR_LOG (
  ERROR_ID         VARCHAR2(40) NOT NULL,
  ERROR_CODE       VARCHAR2(50),
  ERROR_MESSAGE    NVARCHAR2(2000),
  ERROR_LEVEL      VARCHAR2(20) DEFAULT 'ERROR' NOT NULL,
  CREATE_TIME      DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_CJ_SYS_ERROR_LOG PRIMARY KEY (ERROR_ID)
);

-- 6. Administrator Table
CREATE TABLE CJ_ADM_ADMINISTRATOR (
  ADMIN_ID             VARCHAR2(40) NOT NULL,
  USERNAME             VARCHAR2(50) NOT NULL,
  PASSWORD_HASH        VARCHAR2(100) NOT NULL,
  REAL_NAME            NVARCHAR2(50),
  EMAIL                VARCHAR2(100),
  MOBILE               VARCHAR2(20),
  DEPARTMENT           NVARCHAR2(100),
  POSITION             NVARCHAR2(100),
  AVATAR_URL           NVARCHAR2(300),
  STATUS               NUMBER(1) DEFAULT 1 NOT NULL,
  LOGIN_COUNT          NUMBER(10) DEFAULT 0,
  LAST_LOGIN_TIME      DATE,
  LAST_LOGIN_IP        VARCHAR2(50),
  PASSWORD_ERROR_COUNT NUMBER(3) DEFAULT 0,
  LOCK_TIME            DATE,
  CREATE_TIME          DATE DEFAULT SYSDATE NOT NULL,
  UPDATE_TIME          DATE,
  CONSTRAINT PK_CJ_ADM_ADMINISTRATOR PRIMARY KEY (ADMIN_ID)
);

COMMENT ON TABLE CJ_ADM_ADMINISTRATOR IS '管理员表';
COMMENT ON COLUMN CJ_ADM_ADMINISTRATOR.REAL_NAME IS '真实姓名';
COMMENT ON COLUMN CJ_ADM_ADMINISTRATOR.DEPARTMENT IS '部门';
COMMENT ON COLUMN CJ_ADM_ADMINISTRATOR.POSITION IS '职位';

CREATE UNIQUE INDEX UK_ADMIN_USERNAME ON CJ_ADM_ADMINISTRATOR(USERNAME);

-- 7. Role Table
CREATE TABLE CJ_ADM_ROLE (
  ROLE_ID           VARCHAR2(40) NOT NULL,
  ROLE_NAME         NVARCHAR2(50) NOT NULL,
  ROLE_CODE         VARCHAR2(50) NOT NULL,
  ROLE_TYPE         NUMBER(1) DEFAULT 1 NOT NULL,
  DESCRIPTION       NVARCHAR2(200),
  DATA_SCOPE_TYPE   VARCHAR2(20) DEFAULT 'ALL' NOT NULL,
  STATUS            NUMBER(1) DEFAULT 1 NOT NULL,
  CREATE_TIME       DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_CJ_ADM_ROLE PRIMARY KEY (ROLE_ID)
);

COMMENT ON TABLE CJ_ADM_ROLE IS '角色表';
COMMENT ON COLUMN CJ_ADM_ROLE.ROLE_NAME IS '角色名称';
COMMENT ON COLUMN CJ_ADM_ROLE.DESCRIPTION IS '描述';

CREATE UNIQUE INDEX UK_ROLE_CODE ON CJ_ADM_ROLE(ROLE_CODE);

-- 8. Admin-Role Relation
CREATE TABLE CJ_ADM_ADMIN_ROLE (
  ADMIN_ID  VARCHAR2(40) NOT NULL,
  ROLE_ID   VARCHAR2(40) NOT NULL,
  GRANT_TIME DATE DEFAULT SYSDATE,
  CONSTRAINT PK_CJ_ADM_ADMIN_ROLE PRIMARY KEY (ADMIN_ID, ROLE_ID),
  CONSTRAINT FK_AR_ADMIN FOREIGN KEY (ADMIN_ID) REFERENCES CJ_ADM_ADMINISTRATOR(ADMIN_ID) ON DELETE CASCADE,
  CONSTRAINT FK_AR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES CJ_ADM_ROLE(ROLE_ID) ON DELETE CASCADE
);

-- 9. Role-Menu Permission
CREATE TABLE CJ_ADM_ROLE_MENU (
  ROLE_ID    VARCHAR2(40) NOT NULL,
  MENU_ID    VARCHAR2(40) NOT NULL,
  HAS_VIEW   NUMBER(1) DEFAULT 1,
  HAS_CREATE NUMBER(1) DEFAULT 0,
  HAS_UPDATE NUMBER(1) DEFAULT 0,
  HAS_DELETE NUMBER(1) DEFAULT 0,
  CONSTRAINT PK_CJ_ADM_ROLE_MENU PRIMARY KEY (ROLE_ID, MENU_ID),
  CONSTRAINT FK_RM_ROLE FOREIGN KEY (ROLE_ID) REFERENCES CJ_ADM_ROLE(ROLE_ID) ON DELETE CASCADE,
  CONSTRAINT FK_RM_MENU FOREIGN KEY (MENU_ID) REFERENCES CJ_SYS_MENU(MENU_ID) ON DELETE CASCADE
);

-- 10. Data Permission
CREATE TABLE CJ_ADM_DATA_PERMISSION (
  PERMISSION_ID   VARCHAR2(40) NOT NULL,
  ROLE_ID         VARCHAR2(40) NOT NULL,
  RESOURCE_TYPE   VARCHAR2(20) NOT NULL,
  RESOURCE_ID     VARCHAR2(40) NOT NULL,
  PERMISSION_TYPE VARCHAR2(20) NOT NULL,
  CREATE_TIME     DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_CJ_ADM_DATA_PERMISSION PRIMARY KEY (PERMISSION_ID),
  CONSTRAINT FK_DP_ROLE FOREIGN KEY (ROLE_ID) REFERENCES CJ_ADM_ROLE(ROLE_ID) ON DELETE CASCADE
);

-- 11. Login Log
CREATE TABLE CJ_ADM_LOGIN_LOG (
  LOG_ID       VARCHAR2(40) NOT NULL,
  USER_TYPE    VARCHAR2(10) NOT NULL,
  USER_ID      VARCHAR2(40) NOT NULL,
  USERNAME     VARCHAR2(50) NOT NULL,
  LOGIN_STATUS NUMBER(1) DEFAULT 1 NOT NULL,
  FAIL_REASON  NVARCHAR2(200),
  IP_ADDRESS   VARCHAR2(50),
  LOGIN_TIME   DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_CJ_ADM_LOGIN_LOG PRIMARY KEY (LOG_ID)
);

-- 12. Channel Table
CREATE TABLE CJ_CMS_CHANNEL (
  CHANNEL_ID      VARCHAR2(40) NOT NULL,
  SITE_ID         VARCHAR2(40) NOT NULL,
  PARENT_ID       VARCHAR2(40),
  CHANNEL_NAME    NVARCHAR2(100) NOT NULL,
  CHANNEL_CODE    VARCHAR2(50),
  CHANNEL_TYPE    NUMBER(1) DEFAULT 1 NOT NULL,
  MODEL_ID        VARCHAR2(40),
  LINK_URL        NVARCHAR2(300),
  SEO_TITLE       NVARCHAR2(200),
  SEO_KEYWORDS    NVARCHAR2(500),
  SEO_DESCRIPTION NVARCHAR2(500),
  ORDER_NUM       NUMBER(10) DEFAULT 0,
  IS_SHOW         NUMBER(1) DEFAULT 1 NOT NULL,
  CONTENT_COUNT   NUMBER(10) DEFAULT 0,
  CREATE_USER_ID  VARCHAR2(40) NOT NULL,
  CREATE_TIME     DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_CJ_CMS_CHANNEL PRIMARY KEY (CHANNEL_ID),
  CONSTRAINT FK_CHANNEL_SITE FOREIGN KEY (SITE_ID) REFERENCES CJ_SYS_SITE(SITE_ID),
  CONSTRAINT FK_CHANNEL_PARENT FOREIGN KEY (PARENT_ID) REFERENCES CJ_CMS_CHANNEL(CHANNEL_ID)
);

COMMENT ON TABLE CJ_CMS_CHANNEL IS '栏目表';
COMMENT ON COLUMN CJ_CMS_CHANNEL.CHANNEL_NAME IS '栏目名称';

-- 13. Content Model
CREATE TABLE CJ_CMS_MODEL (
  MODEL_ID       VARCHAR2(40) NOT NULL,
  SITE_ID        VARCHAR2(40) NOT NULL,
  MODEL_NAME     NVARCHAR2(100) NOT NULL,
  MODEL_CODE     VARCHAR2(50) NOT NULL,
  TABLE_NAME     VARCHAR2(50) NOT NULL,
  DESCRIPTION    NVARCHAR2(500),
  CREATE_USER_ID VARCHAR2(40) NOT NULL,
  CREATE_TIME    DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_CJ_CMS_MODEL PRIMARY KEY (MODEL_ID),
  CONSTRAINT FK_MODEL_SITE FOREIGN KEY (SITE_ID) REFERENCES CJ_SYS_SITE(SITE_ID)
);

COMMENT ON TABLE CJ_CMS_MODEL IS '内容模型表';
CREATE UNIQUE INDEX UK_MODEL_CODE ON CJ_CMS_MODEL(MODEL_CODE);

-- 14. Model Field
CREATE TABLE CJ_CMS_MODEL_FIELD (
  FIELD_ID      VARCHAR2(40) NOT NULL,
  MODEL_ID      VARCHAR2(40) NOT NULL,
  FIELD_NAME    NVARCHAR2(100) NOT NULL,
  FIELD_CODE    VARCHAR2(50) NOT NULL,
  FIELD_TYPE    VARCHAR2(20) NOT NULL,
  DEFAULT_VALUE NVARCHAR2(500),
  CREATE_TIME   DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_CJ_CMS_MODEL_FIELD PRIMARY KEY (FIELD_ID),
  CONSTRAINT FK_FIELD_MODEL FOREIGN KEY (MODEL_ID) REFERENCES CJ_CMS_MODEL(MODEL_ID)
);

-- 15. Content Table
CREATE TABLE CJ_CMS_CONTENT (
  CONTENT_ID     VARCHAR2(40) NOT NULL,
  SITE_ID        VARCHAR2(40) NOT NULL,
  CHANNEL_ID     VARCHAR2(40) NOT NULL,
  MODEL_ID       VARCHAR2(40) NOT NULL,
  TITLE          NVARCHAR2(200) NOT NULL,
  SUB_TITLE      NVARCHAR2(200),
  AUTHOR         NVARCHAR2(50),
  SOURCE         NVARCHAR2(100),
  PUBLISH_TIME   DATE,
  STATUS         NUMBER(1) DEFAULT 0 NOT NULL,
  VIEW_COUNT     NUMBER(10) DEFAULT 0,
  SEO_TITLE      NVARCHAR2(200),
  SEO_KEYWORDS   NVARCHAR2(500),
  SEO_DESCRIPTION NVARCHAR2(500),
  CREATE_USER_ID VARCHAR2(40) NOT NULL,
  CREATE_TIME    DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_CJ_CMS_CONTENT PRIMARY KEY (CONTENT_ID),
  CONSTRAINT FK_CONTENT_SITE FOREIGN KEY (SITE_ID) REFERENCES CJ_SYS_SITE(SITE_ID),
  CONSTRAINT FK_CONTENT_CHANNEL FOREIGN KEY (CHANNEL_ID) REFERENCES CJ_CMS_CHANNEL(CHANNEL_ID),
  CONSTRAINT FK_CONTENT_MODEL FOREIGN KEY (MODEL_ID) REFERENCES CJ_CMS_MODEL(MODEL_ID)
);

COMMENT ON TABLE CJ_CMS_CONTENT IS '内容表';
COMMENT ON COLUMN CJ_CMS_CONTENT.TITLE IS '标题';

-- 16. Template Table
CREATE TABLE CJ_CMS_TEMPLATE (
  TEMPLATE_ID    VARCHAR2(40) NOT NULL,
  SITE_ID        VARCHAR2(40) NOT NULL,
  TEMPLATE_NAME  NVARCHAR2(100) NOT NULL,
  TEMPLATE_CODE  VARCHAR2(50),
  FILE_PATH      NVARCHAR2(300) NOT NULL,
  FILE_CONTENT   CLOB,
  VERSION        VARCHAR2(20) DEFAULT '1.0.0' NOT NULL,
  CREATE_USER_ID VARCHAR2(40) NOT NULL,
  CREATE_TIME    DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_CJ_CMS_TEMPLATE PRIMARY KEY (TEMPLATE_ID),
  CONSTRAINT FK_TEMPLATE_SITE FOREIGN KEY (SITE_ID) REFERENCES CJ_SYS_SITE(SITE_ID)
);

-- 17. User Table
CREATE TABLE CJ_USER_USER (
  USER_ID         VARCHAR2(40) NOT NULL,
  USERNAME        VARCHAR2(50) NOT NULL,
  PASSWORD_HASH   VARCHAR2(100) NOT NULL,
  NICKNAME        NVARCHAR2(50),
  REAL_NAME       NVARCHAR2(50),
  EMAIL           VARCHAR2(100),
  MOBILE          VARCHAR2(20),
  GROUP_ID        VARCHAR2(40),
  STATUS          NUMBER(1) DEFAULT 1 NOT NULL,
  LOGIN_COUNT     NUMBER(10) DEFAULT 0,
  REGISTER_IP     VARCHAR2(50),
  REGISTER_TIME   DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_CJ_USER_USER PRIMARY KEY (USER_ID)
);

COMMENT ON TABLE CJ_USER_USER IS '用户表';
CREATE UNIQUE INDEX UK_USER_USERNAME ON CJ_USER_USER(USERNAME);

-- 18. User Group
CREATE TABLE CJ_USER_GROUP (
  GROUP_ID          VARCHAR2(40) NOT NULL,
  GROUP_NAME        NVARCHAR2(50) NOT NULL,
  GROUP_CODE        VARCHAR2(50) NOT NULL,
  DESCRIPTION       NVARCHAR2(200),
  MAX_CONTENT_COUNT NUMBER(10),
  NEED_AUDIT        NUMBER(1) DEFAULT 1 NOT NULL,
  STATUS            NUMBER(1) DEFAULT 1 NOT NULL,
  CREATE_TIME       DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_CJ_USER_GROUP PRIMARY KEY (GROUP_ID)
);

COMMENT ON TABLE CJ_USER_GROUP IS '用户组表';
CREATE UNIQUE INDEX UK_GROUP_CODE ON CJ_USER_GROUP(GROUP_CODE);

-- 19. User Submission
CREATE TABLE CJ_USER_SUBMISSION (
  SUBMISSION_ID VARCHAR2(40) NOT NULL,
  USER_ID       VARCHAR2(40) NOT NULL,
  SITE_ID       VARCHAR2(40) NOT NULL,
  CHANNEL_ID    VARCHAR2(40) NOT NULL,
  TITLE         NVARCHAR2(200) NOT NULL,
  CONTENT       NCLOB,
  STATUS        NUMBER(1) DEFAULT 0 NOT NULL,
  AUDIT_COMMENT NVARCHAR2(500),
  REJECT_REASON NVARCHAR2(500),
  CREATE_TIME   DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_CJ_USER_SUBMISSION PRIMARY KEY (SUBMISSION_ID),
  CONSTRAINT FK_US_USER FOREIGN KEY (USER_ID) REFERENCES CJ_USER_USER(USER_ID),
  CONSTRAINT FK_US_SITE FOREIGN KEY (SITE_ID) REFERENCES CJ_SYS_SITE(SITE_ID),
  CONSTRAINT FK_US_CHANNEL FOREIGN KEY (CHANNEL_ID) REFERENCES CJ_CMS_CHANNEL(CHANNEL_ID)
);

COMMIT;

PROMPT ========================================
PROMPT Tables created successfully!
PROMPT All Chinese fields use NVARCHAR2
PROMTP Full Unicode support enabled
PROMPT ========================================
